services:
  postgres:
    container_name: cursos_de_programacao_postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cursos_de_programacao